package live.nerotv.window.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import live.nerotv.Serwin;
import live.nerotv.window.SerwinFrame;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import java.awt.*;

public class EULAForm extends SerwinFrame {

    private JPanel main;
    private JButton noButton;
    private JButton yesButton;
    private JPanel content;
    private JTextPane textPane;

    public EULAForm() {
        setContentPane(main);
        yesButton.addActionListener(e -> {
            dispose();
            Serwin.acceptEULA();
            Serwin.frame = SerwinFrame.get(new SetupForm());
        });
        noButton.addActionListener(e -> {
            dispose();
            ErrorForm form = (ErrorForm) SerwinFrame.get(new ErrorForm("You need to accept the EULA!"));
            form.setError("If you want to create a Minecraft server you MUST accept the EULA. Without you accepting it, you are not permitted to create a server.");
            Dimension size = new Dimension(500, 145);
            form.setMinimumSize(size);
            form.setSize(size);
            form.setMaximumSize(size);
            form.setResizable(false);
            form.setLocationRelativeTo(null);
            form.setVisible(true);
        });
        setTitle("SerwiN v" + Serwin.serwin + " EULA-Check");
        textPane.setContentType("text/html");
        textPane.setText("<html>Have you read the Minecraft EULA and do you accept it?<br><a href='https://www.minecraft.net/eula'>https://www.minecraft.net/eula</a></html>");
        textPane.addHyperlinkListener(e -> {
            if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                try {
                    Desktop.getDesktop().browse(e.getURL().toURI());
                } catch (Exception ignore) {
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        content = new JPanel();
        content.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.add(content, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        textPane = new JTextPane();
        textPane.setEditable(false);
        textPane.setText("loading..");
        content.add(textPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        yesButton = new JButton();
        yesButton.setText("Yes");
        main.add(yesButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noButton = new JButton();
        noButton.setText("No");
        main.add(noButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

}
