package live.nerotv.window.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import live.nerotv.Serwin;
import live.nerotv.window.SerwinFrame;

import javax.swing.*;
import java.awt.*;
import java.net.URI;

public class LinkForm extends SerwinFrame {

    private JPanel main;
    private JPanel content;
    private JButton open;
    private JTextPane text;

    private String url;

    public LinkForm(String URL) {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(main);
        url = URL;
        open.addActionListener(e -> {
            open();
        });
        Dimension size = new Dimension(500, 250);
        setMinimumSize(size);
        setSize(size);
        setMaximumSize(size);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public void setText(String text) {
        this.text.setContentType("text/html");
        this.text.setText(text);
    }

    public void setButton(String text) {
        open.setText(text);
    }

    public void setURL(String URL) {
        url = URL;
    }

    private void open() {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(URI.create(url));
            } catch (Exception e_) {
                Serwin.logger.error("Couldn't open URL " + url + ": " + e_);
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        content = new JPanel();
        content.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.add(content, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        text = new JTextPane();
        text.setContentType("text/plain");
        text.setEditable(false);
        text.setText("loading...");
        content.add(text, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        open = new JButton();
        open.setText("Open");
        main.add(open, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
