package live.nerotv.window.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import live.nerotv.Serwin;
import live.nerotv.window.SerwinFrame;

import javax.swing.*;
import java.awt.*;

public class LoadingForm extends SerwinFrame {

    private JPanel main;
    private JPanel content;
    private JTextPane text;
    private JProgressBar progress;
    private String title = "something";
    private String text_ = "loading...";

    public LoadingForm() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(main);
        setTitle("SerwiN v" + Serwin.serwin + " is loading " + title + "...");
        progress.setIndeterminate(true);
        repaint();
    }

    public String getTitleName() {
        return title;
    }

    public void setName(String title) {
        this.title = title;
        setTitle("SerwiN v" + Serwin.serwin + " is loading " + title + "...");
    }

    public String getText() {
        return text_;
    }

    public void setText(String text) {
        this.text_ = text;
        this.text.setContentType("text/html");
        this.text.setText(text);
        repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        content = new JPanel();
        content.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        main.add(content, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        text = new JTextPane();
        text.setEditable(false);
        text.setText("loading...");
        content.add(text, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        progress = new JProgressBar();
        progress.setValue(0);
        content.add(progress, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

}
